### ISSUE TITLE
HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by DonniK** [skleinei/alfred-confluence#1]
I know I'm using the right username/password/base URL but I get an error when trying to search. Could this error be related to my specific account privileges? 
![screen shot 2017-05-10 at 3 08 15 pm](https://cloud.githubusercontent.com/assets/19958618/25916430/929840b6-3592-11e7-8771-722971dd0c55.png)

**Comment by skleinei** [comment]
This is not related to account privileges. There were some issues with changes in Confluence Cloud, which now requires tokes. Please upgrade to 1.0.3 and use an API token (https://confluence.atlassian.com/cloud/api-tokens-938839638.html).
