### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by hoetmaaiers** [skleinei/alfred-confluence#3]
I receive an error like `No JSON object could be decoded`. Can this be due to my Confluence account being attached to a Google Business account?

![screen shot 2017-08-21 at 10 27 47](https://user-images.githubusercontent.com/468045/29510249-6965e6d4-865b-11e7-9f13-07779fe16a84.png)

**Comment by gtheys** [comment]
+1

**Comment by skleinei** [comment]
Please try again with version 1.0.3. Authentication which may have caused this issue.

**Comment by skleinei** [comment]
@gtheys, @hoetmaaiers, I'm closing this issue now. Let me know, if you continue to see this issue.
