### ISSUE TITLE
HTTP 404 Error: Not Found

### ISSUE THREAD

**Issue by oorahduc** [skleinei/alfred-confluence#4]
<img width="565" alt="screen shot 2017-12-28 at 1 43 16 pm" src="https://user-images.githubusercontent.com/11790611/34424028-2c9bcb26-ebd5-11e7-97a6-101a37e7607e.png">

Root URL and credentials are correct. It should be noted that this could be related to Confluence's new layout.

**Comment by jan-aoe** [comment]
Late answer – had the same problem. Simply try removing the trailing slash from the base URL when configuring `confluence_baseurl`. Solved the problem for me.

E.g. this should work:
`https://www.example.com/wiki`
that won't:
`https://www.example.com/wiki/`

**Comment by skleinei** [comment]
The issue with the trailing slashes should be fixed in version 1.0.3.
